services:
  - type: web
    name: cerulik-ai-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: ***REMOVED***
        sync: false
      - key: ***REMOVED***
        sync: false
      - key: ***REMOVED***
        sync: false
      - key: ***REMOVED***
        sync: false
    autoDeploy: true
    region: frankfurt
