services:
  - type: web
    name: cerulik-ai-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: AUTH_USERNAME
        sync: false
      - key: AUTH_PASSWORD
        sync: false
    autoDeploy: true
    region: frankfurt
